[project]
name = "pudimi-mpi"
version = "0.1.3"
description = "Wrapper C++ MPI transparente com suporte a ULFM"
authors = [
    { name = "Angelo Marcelino", email = "amc.marcelino.cordeiro@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "numpy (<2.0)",
    "mpi4py (>=3.1.5)"
]


[tool.poetry]
packages = [{ include = "pudimi_mpi" }]

include = [
    { path = "cpp_lib/include/*.hpp", format = "sdist" },
    { path = "cpp_lib/src/*.cpp", format = "sdist" },
    { path = "pudimi_mpi/*.pxd", format = "sdist" },
    { path = "pudimi_mpi/*.pyi", format = ["sdist", "wheel"] },
    { path = "pudimi_mpi/py.typed", format = ["sdist", "wheel"] },
]


[build-system]
requires = [
    "scikit-build-core>=0.9",
    "cython>=3.0,<4.0",
    "numpy<2.0",
    "mpi4py>=3.1.5",
]
build-backend = "scikit_build_core.build"


[tool.scikit-build]
wheel.packages = ["pudimi_mpi"]

[tool.scikit-build.cmake]
minimum-version = "3.18"
build-type = "Release"


[dependency-groups]
dev = [
    "cython (>=3.0,<4.0)",
    "setuptools (>=80.0.0)",
    "poethepoet (>=0.42.1,<0.43.0)",
    "ruff (>=0.15.4,<0.16.0)",
]


[tool.poe.tasks]
build-ext = "pip install -e ."
test-mpi = "mpirun -n 2 python test_mpi.py"
test-numpy = "mpirun -n 2 python test_numpy_mpi.py"