[project]
name = "pudimi-mpi"
version = "0.1.7"
description = "Wrapper C++ MPI transparente com suporte a ULFM"
authors = [
    { name = "Angelo Marcelino", email = "amc.marcelino.cordeiro@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.11"
# Dependências de runtime (o que o usuário final precisa)
dependencies = ["numpy (<2.0)"]

[tool.poetry]
packages = [{ include = "pudimi_mpi" }]
include = [
    { path = "cpp_lib/include/*.hpp", format = "sdist" },
    { path = "cpp_lib/src/*.cpp", format = "sdist" },
    { path = "pudimi_mpi/*.pxd", format = "sdist" },
    { path = "pudimi_mpi/*.pyi", format = [
        "sdist",
        "wheel",
    ] },
    { path = "pudimi_mpi/py.typed", format = [
        "sdist",
        "wheel",
    ] },
    { path = "pudimi_mpi/*.so", format = "wheel" },
]
exclude = ["pudimi_mpi/*.html", "pudimi_mpi/*.pyx", "pudimi_mpi/*.pxd"]
build = "build.py"

[build-system]
# mpi4py e numpy DEVEM estar aqui para prover headers no build isolado
requires = [
    "poetry-core>=2.0.0",
    "setuptools>=80.0.0",
    "Cython>=3.0,<4.0",
    "numpy<2.0",
    "mpi4py==3.1.4",
]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "cython (>=3.0,<4.0)",
    "setuptools (>=80.0.0)",
    "poethepoet (>=0.42.1,<0.43.0)",
    "ruff (>=0.15.4,<0.16.0)",
    "mpi4py (==3.1.4)",
]

[tool.poe.tasks]
# Compila localmente usando o OpenMPI em /opt/openmpi-5.0.8
build-ext = "python build.py build_ext --inplace"

# Executa teste de redução com 2 processos para validar a comunicação
run-test = "/opt/openmpi-5.0.8/bin/mpirun -n 2 python test_mpi.py"

run-numpy-test = "/opt/openmpi-5.0.8/bin/mpirun -n 2 python test_numpy_mpi.py"

# Tarefa completa: limpa, compila e testa
test = ["build-ext", "run-test", "run-numpy-test"]

build-wheel = ["build-ext", { cmd = "poetry build" }]

clean = "rm -rf build/ dist/ pudimi_mpi/*.so pudimi_mpi/*.cpp pudimi_mpi/*.html"

rebuild-wheel = ["clean", "build-wheel"]
